### ISSUE TITLE
Training Error only on GPU: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by lukasHoel** [daooshee/ReReVST-Code#2]
Hi, thanks for making the nice code-base available! :)

I try to train as mentioned in 1.2.2 of the Readme:

`python train.py --batchSize 1 --continue_training --content_data <path/to/custom/content/data> --style_data <path/to/custom/styles> --dynamic_filter --both_sty_con --relax_style --style_content_loss --contentWeight 1 --recon_loss --tv_loss --temporal_loss --data_sigma --data_w --outf . --cuda --gpu 0`

It works when not training on GPU (by leaving away the last two arguments), but I get the error when trying it on a GPU.

PyTorch Version: `1.8.1+cu111`

I think maybe some inputs are not moved correctly to cuda during the training pipeline?
But I could not find the mistake myself.

Any help to locate the error would be appreciated! :)

```
Traceback (most recent call last):
  File "train.py", line 414, in <module>
    Loss.backward()
  File "/home/teampc/anaconda3/envs/nvs/lib/python3.8/site-packages/torch/tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/teampc/anaconda3/envs/nvs/lib/python3.8/site-packages/torch/autograd/__init__.py", line 145, in backward
    Variable._execution_engine.run_backward(
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([2, 512, 32, 32], dtype=torch.float, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(512, 32, kernel_size=[3, 3], padding=[1, 1], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().float()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams 
    data_type = CUDNN_DATA_FLOAT
    padding = [1, 1, 0]
    stride = [1, 1, 0]
    dilation = [1, 1, 0]
    groups = 1
    deterministic = false
    allow_tf32 = true
input: TensorDescriptor 0x7f516c0c0e60
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 512, 32, 32, 
    strideA = 524288, 1024, 32, 1, 
output: TensorDescriptor 0x7f516c0bed60
    type = CUDNN_DATA_FLOAT
    nbDims = 4
    dimA = 2, 32, 32, 32, 
    strideA = 32768, 1024, 32, 1, 
weight: FilterDescriptor 0x7f516c0bf040
    type = CUDNN_DATA_FLOAT
    tensor_format = CUDNN_TENSOR_NCHW
    nbDims = 4
    dimA = 32, 512, 3, 3, 
Pointer addresses: 
    input: 0x7f5239980000
    output: 0x7f52c6980000
    weight: 0x7f52c6c90000
Additional pointer addresses: 
    grad_output: 0x7f52c6980000
    grad_weight: 0x7f52c6c90000
Backward filter algorithm: 5
```

**Comment by daooshee** [comment]
Sorry that I'm also not familiar with this problem. According to [this issue](https://github.com/NVIDIA/tacotron2/issues/109), `CUDNN_STATUS_EXECUTION_FAILED` might be caused by CUDA or PyTorch versions. Can you successfully run other PyTorch GPU codes?

Or maybe it is caused by some specific losses? For example, try removing the --relax_style loss?

**Comment by lukasHoel** [comment]
Thanks for your fast reply!
Yes, I can run other PyTorch GPU codes.
I tried playing around with the losses, but found no combination that works. Not using `--relax_style` also did not solve the problem, unfortunately.

I am providing custom image folders for content/style, but because this is working on CPU training, I don't think this is the issue.

Apart from that, only my PyTorch and CUDA version might be different to yours. Which PyTorch version are you using?

**Comment by daooshee** [comment]
Hi, sorry for my late reply. I tried two environments. One is PyTorch 1.6:
```
cuda in /usr/local                 10.1
torch.__version__                  1.6.0
torch.version.cuda                 10.2
torch.backends.cudnn.version()     7605
```
The other is PyTorch 1.7:
```
cuda in /usr/local                 11.1
torch.__version__                  1.7.1
torch.version.cuda                 10.2
torch.backends.cudnn.version()     7605
```
Both of them work. Hope it helps~

**Comment by lukasHoel** [comment]
Hi, sorry for the late reply. I figured out the problem, it was PyTorch 1.8. Works as you described with 1.7
Thanks for your help!
